version: '3.8'
services:
    postgres_server:
        image: postgres
        hostname: postgres_server
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_DB=$POSTGRES_DB
        ports:
            - '$POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT'
        volumes:
            - ./src/utils/db/init/main.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
            - db:/var/lib/postgresql/data
        cap_add:
            - SYS_NICE

    app:
        depends_on:
            - postgres_server
        restart: unless-stopped
        build: .
        ports:
            - '$APP_PORT:$APP_DOCKER_PORT'
        environment:
            - POSTGRES_HOST=$POSTGRES_HOST
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=$POSTGRES_USER
            - APP_PORT=$APP_PORT
            - NEXT_PUBLIC_VERCEL_URL=$NEXT_PUBLIC_VERCEL_URL
            - APP_ENV=$APP_ENV
            - SECRET_KEY=$SECRET_KEY
        stdin_open: true
        tty: true
volumes:
    db:
